version: '2'
services:
  # DB
  mysql: # これは自由につけても良い名前
    container_name: "mysql2"
    image: mysql:5.6
    ports:
      - '3306:3306' # デバッグ用。
    environment:
      MYSQL_ROOT_PASSWORD: root
  # php
  php:
    container_name: "php2"
    image: php:7.1-apache
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html
    links:
      - mysql